# Generated by Django 2.2.5 on 2021-04-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_brand',
            field=models.CharField(max_length=100),
        ),
    ]
